# https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
---
apiVersion: v1
kind: Pod
metadata:
  name: pods-image-pull-secret-pod
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: pods-image-pull-secret-container
  imagepullsecrets:
    - name: regcred  # does not exist, create with instructions above
