---
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-busybox
spec:
  containers:
    - image: busybox
      command:
        - sleep
        - "3600"
      name: busybox1
    - image: busybox
      command:
        - sleep
        - "3601"
      name: busybox2
