apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    app: busybox1
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox1
  restartPolicy: Always
  - image: busybox
    command:
      - sleep
      - "3601"
    imagePullPolicy: IfNotPresent
    name: busybox2
  restartPolicy: Always
