---
apiVersion: v1
kind: Pod
metadata:
  name: simple-busybox
  labels:
    app: simple-busybox
spec:
  containers:
    - image: busybox
      command:
        - sleep
        - "3600"
      name: busybox
