---
apiVersion: v1
kind: Secret
metadata:
  name: simple-secret
type: Opaque
stringData:
  config.yaml: |-
    apiUrl: "https://my.api.com/api/v1"
    username: ausername
    password: apassword
---
apiVersion: v1
kind: Pod
metadata:
  name: simple-secret
spec:
  containers:
  - name: simple-secret-redis
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: simple-secret
