---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-simple-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-simple
  template:
    metadata:
      labels:
        app: deployment-simple
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
          - sleep
          - "3600"
