---
apiVersion: v1
kind: Pod
metadata:
  name: broken-pod-no-command
  labels:
    app: broken-pod-no-command
spec:
  containers:
    - image: busybox
      # command:
      #   - sleep
      #   - "3600"
      imagePullPolicy: IfNotPresent
      name: busybox
  restartPolicy: Always
