---
apiVersion: v1
kind: Pod
metadata:
  name: pods-resource-request-pod
spec:
  containers:
    - name: pods-resource-request-container
      image: busybox
      args:
        - sleep
        - "600"
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
      resources:
        requests:
          memory: "20000Mi"
          cpu: "99999m"
