---
apiVersion: v1
kind: Secret
metadata:
  name: simple-secret
type: Opaque
stringData:
  config.yaml: |-
    username: ausername
    password: apassword
---
apiVersion: v1
kind: Pod
metadata:
  name: simple-secret-pod
spec:
  containers:
    - name: simple-secret-busybox
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: simple-secret-volume
          mountPath: "/etc/simple-secret"
  volumes:
    - name: simple-secret-volume
      secret:
        secretName: simple-secret
